/*
 * File: app/view/ChannelFormPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AmbientMixer.view.ChannelFormPanel', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.field.File',
        'Ext.field.Toggle',
        'Ext.field.Spinner',
        'Ext.Button',
        'Ext.field.DatePicker',
        'Ext.picker.Date'
    ],

    config: {
        items: [
            {
                xtype: 'filefield',
                label: 'Field'
            },
            {
                xtype: 'sliderfield',
                label: 'Volume',
                value: [
                    50
                ]
            },
            {
                xtype: 'sliderfield',
                label: 'Balance',
                value: [
                    0
                ],
                increment: 0.1,
                maxValue: 1,
                minValue: -1
            },
            {
                xtype: 'togglefield',
                label: 'Random'
            },
            {
                xtype: 'spinnerfield',
                label: 'Delay',
                minValue: 0,
                stepValue: 1
            },
            {
                xtype: 'button',
                iconCls: 'action',
                text: 'Play'
            },
            {
                xtype: 'selectfield',
                label: 'Field'
            },
            {
                xtype: 'datepickerfield',
                label: 'Field',
                placeHolder: 'mm/dd/yyyy'
            },
            {
                xtype: 'sliderfield',
                label: 'Field'
            }
        ]
    }

});