/*
 * File: app/controller/ChannelController.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AmbientMixer.controller.ChannelController', {
    extend: 'Ext.app.Controller',

    statics: {
        getRandomInt: function(min, max) {
            if(min === max){
                return min;
            }

            return Math.floor(Math.random() * (max - min + 1)) + min;
        }
    },

    config: {
    }
});