/*
 * File: app/store/Mixes.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AmbientMixer.store.Mixes', {
    extend: 'Ext.data.Store',

    requires: [
        'AmbientMixer.model.Mix',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    config: {
        model: 'AmbientMixer.model.Mix',
        storeId: 'Mixes',
        proxy: {
            type: 'ajax',
            url: 'mixes.js',
            reader: {
                type: 'json'
            }
        }
    }
});